// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/image_info.proto

public final class ImageInfo {
  private ImageInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ImagesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Images)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Images.Image images = 1;</code>
     */
    java.util.List<ImageInfo.Images.Image> 
        getImagesList();
    /**
     * <code>repeated .Images.Image images = 1;</code>
     */
    ImageInfo.Images.Image getImages(int index);
    /**
     * <code>repeated .Images.Image images = 1;</code>
     */
    int getImagesCount();
    /**
     * <code>repeated .Images.Image images = 1;</code>
     */
    java.util.List<? extends ImageInfo.Images.ImageOrBuilder> 
        getImagesOrBuilderList();
    /**
     * <code>repeated .Images.Image images = 1;</code>
     */
    ImageInfo.Images.ImageOrBuilder getImagesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Images}
   */
  public static final class Images extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Images)
      ImagesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Images.newBuilder() to construct.
    private Images(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Images() {
      images_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Images();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Images(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                images_ = new java.util.ArrayList<ImageInfo.Images.Image>();
                mutable_bitField0_ |= 0x00000001;
              }
              images_.add(
                  input.readMessage(ImageInfo.Images.Image.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          images_ = java.util.Collections.unmodifiableList(images_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ImageInfo.internal_static_Images_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ImageInfo.internal_static_Images_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ImageInfo.Images.class, ImageInfo.Images.Builder.class);
    }

    public interface ImageOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Images.Image)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string filename = 1;</code>
       * @return Whether the filename field is set.
       */
      boolean hasFilename();
      /**
       * <code>optional string filename = 1;</code>
       * @return The filename.
       */
      java.lang.String getFilename();
      /**
       * <code>optional string filename = 1;</code>
       * @return The bytes for filename.
       */
      com.google.protobuf.ByteString
          getFilenameBytes();

      /**
       * <code>optional int64 size = 2;</code>
       * @return Whether the size field is set.
       */
      boolean hasSize();
      /**
       * <code>optional int64 size = 2;</code>
       * @return The size.
       */
      long getSize();

      /**
       * <code>optional int64 createdTime = 3;</code>
       * @return Whether the createdTime field is set.
       */
      boolean hasCreatedTime();
      /**
       * <code>optional int64 createdTime = 3;</code>
       * @return The createdTime.
       */
      long getCreatedTime();

      /**
       * <code>optional int64 modifiedTime = 4;</code>
       * @return Whether the modifiedTime field is set.
       */
      boolean hasModifiedTime();
      /**
       * <code>optional int64 modifiedTime = 4;</code>
       * @return The modifiedTime.
       */
      long getModifiedTime();
    }
    /**
     * Protobuf type {@code Images.Image}
     */
    public static final class Image extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Images.Image)
        ImageOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Image.newBuilder() to construct.
      private Image(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Image() {
        filename_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Image();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Image(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                filename_ = bs;
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                size_ = input.readInt64();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                createdTime_ = input.readInt64();
                break;
              }
              case 32: {
                bitField0_ |= 0x00000008;
                modifiedTime_ = input.readInt64();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ImageInfo.internal_static_Images_Image_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ImageInfo.internal_static_Images_Image_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ImageInfo.Images.Image.class, ImageInfo.Images.Image.Builder.class);
      }

      private int bitField0_;
      public static final int FILENAME_FIELD_NUMBER = 1;
      private volatile java.lang.Object filename_;
      /**
       * <code>optional string filename = 1;</code>
       * @return Whether the filename field is set.
       */
      @java.lang.Override
      public boolean hasFilename() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string filename = 1;</code>
       * @return The filename.
       */
      @java.lang.Override
      public java.lang.String getFilename() {
        java.lang.Object ref = filename_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            filename_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string filename = 1;</code>
       * @return The bytes for filename.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getFilenameBytes() {
        java.lang.Object ref = filename_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filename_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int SIZE_FIELD_NUMBER = 2;
      private long size_;
      /**
       * <code>optional int64 size = 2;</code>
       * @return Whether the size field is set.
       */
      @java.lang.Override
      public boolean hasSize() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int64 size = 2;</code>
       * @return The size.
       */
      @java.lang.Override
      public long getSize() {
        return size_;
      }

      public static final int CREATEDTIME_FIELD_NUMBER = 3;
      private long createdTime_;
      /**
       * <code>optional int64 createdTime = 3;</code>
       * @return Whether the createdTime field is set.
       */
      @java.lang.Override
      public boolean hasCreatedTime() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int64 createdTime = 3;</code>
       * @return The createdTime.
       */
      @java.lang.Override
      public long getCreatedTime() {
        return createdTime_;
      }

      public static final int MODIFIEDTIME_FIELD_NUMBER = 4;
      private long modifiedTime_;
      /**
       * <code>optional int64 modifiedTime = 4;</code>
       * @return Whether the modifiedTime field is set.
       */
      @java.lang.Override
      public boolean hasModifiedTime() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional int64 modifiedTime = 4;</code>
       * @return The modifiedTime.
       */
      @java.lang.Override
      public long getModifiedTime() {
        return modifiedTime_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, filename_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          output.writeInt64(2, size_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          output.writeInt64(3, createdTime_);
        }
        if (((bitField0_ & 0x00000008) != 0)) {
          output.writeInt64(4, modifiedTime_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, filename_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(2, size_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(3, createdTime_);
        }
        if (((bitField0_ & 0x00000008) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(4, modifiedTime_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof ImageInfo.Images.Image)) {
          return super.equals(obj);
        }
        ImageInfo.Images.Image other = (ImageInfo.Images.Image) obj;

        if (hasFilename() != other.hasFilename()) return false;
        if (hasFilename()) {
          if (!getFilename()
              .equals(other.getFilename())) return false;
        }
        if (hasSize() != other.hasSize()) return false;
        if (hasSize()) {
          if (getSize()
              != other.getSize()) return false;
        }
        if (hasCreatedTime() != other.hasCreatedTime()) return false;
        if (hasCreatedTime()) {
          if (getCreatedTime()
              != other.getCreatedTime()) return false;
        }
        if (hasModifiedTime() != other.hasModifiedTime()) return false;
        if (hasModifiedTime()) {
          if (getModifiedTime()
              != other.getModifiedTime()) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasFilename()) {
          hash = (37 * hash) + FILENAME_FIELD_NUMBER;
          hash = (53 * hash) + getFilename().hashCode();
        }
        if (hasSize()) {
          hash = (37 * hash) + SIZE_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getSize());
        }
        if (hasCreatedTime()) {
          hash = (37 * hash) + CREATEDTIME_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getCreatedTime());
        }
        if (hasModifiedTime()) {
          hash = (37 * hash) + MODIFIEDTIME_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getModifiedTime());
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static ImageInfo.Images.Image parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ImageInfo.Images.Image parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ImageInfo.Images.Image parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ImageInfo.Images.Image parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ImageInfo.Images.Image parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ImageInfo.Images.Image parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ImageInfo.Images.Image parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ImageInfo.Images.Image parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static ImageInfo.Images.Image parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static ImageInfo.Images.Image parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static ImageInfo.Images.Image parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ImageInfo.Images.Image parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(ImageInfo.Images.Image prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Images.Image}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Images.Image)
          ImageInfo.Images.ImageOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ImageInfo.internal_static_Images_Image_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ImageInfo.internal_static_Images_Image_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  ImageInfo.Images.Image.class, ImageInfo.Images.Image.Builder.class);
        }

        // Construct using ImageInfo.Images.Image.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          filename_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          size_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000002);
          createdTime_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000004);
          modifiedTime_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ImageInfo.internal_static_Images_Image_descriptor;
        }

        @java.lang.Override
        public ImageInfo.Images.Image getDefaultInstanceForType() {
          return ImageInfo.Images.Image.getDefaultInstance();
        }

        @java.lang.Override
        public ImageInfo.Images.Image build() {
          ImageInfo.Images.Image result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public ImageInfo.Images.Image buildPartial() {
          ImageInfo.Images.Image result = new ImageInfo.Images.Image(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            to_bitField0_ |= 0x00000001;
          }
          result.filename_ = filename_;
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.size_ = size_;
            to_bitField0_ |= 0x00000002;
          }
          if (((from_bitField0_ & 0x00000004) != 0)) {
            result.createdTime_ = createdTime_;
            to_bitField0_ |= 0x00000004;
          }
          if (((from_bitField0_ & 0x00000008) != 0)) {
            result.modifiedTime_ = modifiedTime_;
            to_bitField0_ |= 0x00000008;
          }
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof ImageInfo.Images.Image) {
            return mergeFrom((ImageInfo.Images.Image)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(ImageInfo.Images.Image other) {
          if (other == ImageInfo.Images.Image.getDefaultInstance()) return this;
          if (other.hasFilename()) {
            bitField0_ |= 0x00000001;
            filename_ = other.filename_;
            onChanged();
          }
          if (other.hasSize()) {
            setSize(other.getSize());
          }
          if (other.hasCreatedTime()) {
            setCreatedTime(other.getCreatedTime());
          }
          if (other.hasModifiedTime()) {
            setModifiedTime(other.getModifiedTime());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          ImageInfo.Images.Image parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (ImageInfo.Images.Image) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object filename_ = "";
        /**
         * <code>optional string filename = 1;</code>
         * @return Whether the filename field is set.
         */
        public boolean hasFilename() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>optional string filename = 1;</code>
         * @return The filename.
         */
        public java.lang.String getFilename() {
          java.lang.Object ref = filename_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              filename_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string filename = 1;</code>
         * @return The bytes for filename.
         */
        public com.google.protobuf.ByteString
            getFilenameBytes() {
          java.lang.Object ref = filename_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            filename_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string filename = 1;</code>
         * @param value The filename to set.
         * @return This builder for chaining.
         */
        public Builder setFilename(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          filename_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string filename = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearFilename() {
          bitField0_ = (bitField0_ & ~0x00000001);
          filename_ = getDefaultInstance().getFilename();
          onChanged();
          return this;
        }
        /**
         * <code>optional string filename = 1;</code>
         * @param value The bytes for filename to set.
         * @return This builder for chaining.
         */
        public Builder setFilenameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          filename_ = value;
          onChanged();
          return this;
        }

        private long size_ ;
        /**
         * <code>optional int64 size = 2;</code>
         * @return Whether the size field is set.
         */
        @java.lang.Override
        public boolean hasSize() {
          return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>optional int64 size = 2;</code>
         * @return The size.
         */
        @java.lang.Override
        public long getSize() {
          return size_;
        }
        /**
         * <code>optional int64 size = 2;</code>
         * @param value The size to set.
         * @return This builder for chaining.
         */
        public Builder setSize(long value) {
          bitField0_ |= 0x00000002;
          size_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int64 size = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearSize() {
          bitField0_ = (bitField0_ & ~0x00000002);
          size_ = 0L;
          onChanged();
          return this;
        }

        private long createdTime_ ;
        /**
         * <code>optional int64 createdTime = 3;</code>
         * @return Whether the createdTime field is set.
         */
        @java.lang.Override
        public boolean hasCreatedTime() {
          return ((bitField0_ & 0x00000004) != 0);
        }
        /**
         * <code>optional int64 createdTime = 3;</code>
         * @return The createdTime.
         */
        @java.lang.Override
        public long getCreatedTime() {
          return createdTime_;
        }
        /**
         * <code>optional int64 createdTime = 3;</code>
         * @param value The createdTime to set.
         * @return This builder for chaining.
         */
        public Builder setCreatedTime(long value) {
          bitField0_ |= 0x00000004;
          createdTime_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int64 createdTime = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearCreatedTime() {
          bitField0_ = (bitField0_ & ~0x00000004);
          createdTime_ = 0L;
          onChanged();
          return this;
        }

        private long modifiedTime_ ;
        /**
         * <code>optional int64 modifiedTime = 4;</code>
         * @return Whether the modifiedTime field is set.
         */
        @java.lang.Override
        public boolean hasModifiedTime() {
          return ((bitField0_ & 0x00000008) != 0);
        }
        /**
         * <code>optional int64 modifiedTime = 4;</code>
         * @return The modifiedTime.
         */
        @java.lang.Override
        public long getModifiedTime() {
          return modifiedTime_;
        }
        /**
         * <code>optional int64 modifiedTime = 4;</code>
         * @param value The modifiedTime to set.
         * @return This builder for chaining.
         */
        public Builder setModifiedTime(long value) {
          bitField0_ |= 0x00000008;
          modifiedTime_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int64 modifiedTime = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearModifiedTime() {
          bitField0_ = (bitField0_ & ~0x00000008);
          modifiedTime_ = 0L;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Images.Image)
      }

      // @@protoc_insertion_point(class_scope:Images.Image)
      private static final ImageInfo.Images.Image DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new ImageInfo.Images.Image();
      }

      public static ImageInfo.Images.Image getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Image>
          PARSER = new com.google.protobuf.AbstractParser<Image>() {
        @java.lang.Override
        public Image parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Image(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Image> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Image> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public ImageInfo.Images.Image getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int IMAGES_FIELD_NUMBER = 1;
    private java.util.List<ImageInfo.Images.Image> images_;
    /**
     * <code>repeated .Images.Image images = 1;</code>
     */
    @java.lang.Override
    public java.util.List<ImageInfo.Images.Image> getImagesList() {
      return images_;
    }
    /**
     * <code>repeated .Images.Image images = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends ImageInfo.Images.ImageOrBuilder> 
        getImagesOrBuilderList() {
      return images_;
    }
    /**
     * <code>repeated .Images.Image images = 1;</code>
     */
    @java.lang.Override
    public int getImagesCount() {
      return images_.size();
    }
    /**
     * <code>repeated .Images.Image images = 1;</code>
     */
    @java.lang.Override
    public ImageInfo.Images.Image getImages(int index) {
      return images_.get(index);
    }
    /**
     * <code>repeated .Images.Image images = 1;</code>
     */
    @java.lang.Override
    public ImageInfo.Images.ImageOrBuilder getImagesOrBuilder(
        int index) {
      return images_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < images_.size(); i++) {
        output.writeMessage(1, images_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < images_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, images_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ImageInfo.Images)) {
        return super.equals(obj);
      }
      ImageInfo.Images other = (ImageInfo.Images) obj;

      if (!getImagesList()
          .equals(other.getImagesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getImagesCount() > 0) {
        hash = (37 * hash) + IMAGES_FIELD_NUMBER;
        hash = (53 * hash) + getImagesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ImageInfo.Images parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ImageInfo.Images parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ImageInfo.Images parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ImageInfo.Images parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ImageInfo.Images parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ImageInfo.Images parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ImageInfo.Images parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ImageInfo.Images parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ImageInfo.Images parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ImageInfo.Images parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ImageInfo.Images parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ImageInfo.Images parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ImageInfo.Images prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Images}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Images)
        ImageInfo.ImagesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ImageInfo.internal_static_Images_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ImageInfo.internal_static_Images_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ImageInfo.Images.class, ImageInfo.Images.Builder.class);
      }

      // Construct using ImageInfo.Images.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getImagesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (imagesBuilder_ == null) {
          images_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          imagesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ImageInfo.internal_static_Images_descriptor;
      }

      @java.lang.Override
      public ImageInfo.Images getDefaultInstanceForType() {
        return ImageInfo.Images.getDefaultInstance();
      }

      @java.lang.Override
      public ImageInfo.Images build() {
        ImageInfo.Images result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ImageInfo.Images buildPartial() {
        ImageInfo.Images result = new ImageInfo.Images(this);
        int from_bitField0_ = bitField0_;
        if (imagesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            images_ = java.util.Collections.unmodifiableList(images_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.images_ = images_;
        } else {
          result.images_ = imagesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ImageInfo.Images) {
          return mergeFrom((ImageInfo.Images)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ImageInfo.Images other) {
        if (other == ImageInfo.Images.getDefaultInstance()) return this;
        if (imagesBuilder_ == null) {
          if (!other.images_.isEmpty()) {
            if (images_.isEmpty()) {
              images_ = other.images_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureImagesIsMutable();
              images_.addAll(other.images_);
            }
            onChanged();
          }
        } else {
          if (!other.images_.isEmpty()) {
            if (imagesBuilder_.isEmpty()) {
              imagesBuilder_.dispose();
              imagesBuilder_ = null;
              images_ = other.images_;
              bitField0_ = (bitField0_ & ~0x00000001);
              imagesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getImagesFieldBuilder() : null;
            } else {
              imagesBuilder_.addAllMessages(other.images_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ImageInfo.Images parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ImageInfo.Images) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<ImageInfo.Images.Image> images_ =
        java.util.Collections.emptyList();
      private void ensureImagesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          images_ = new java.util.ArrayList<ImageInfo.Images.Image>(images_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ImageInfo.Images.Image, ImageInfo.Images.Image.Builder, ImageInfo.Images.ImageOrBuilder> imagesBuilder_;

      /**
       * <code>repeated .Images.Image images = 1;</code>
       */
      public java.util.List<ImageInfo.Images.Image> getImagesList() {
        if (imagesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(images_);
        } else {
          return imagesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Images.Image images = 1;</code>
       */
      public int getImagesCount() {
        if (imagesBuilder_ == null) {
          return images_.size();
        } else {
          return imagesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Images.Image images = 1;</code>
       */
      public ImageInfo.Images.Image getImages(int index) {
        if (imagesBuilder_ == null) {
          return images_.get(index);
        } else {
          return imagesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Images.Image images = 1;</code>
       */
      public Builder setImages(
          int index, ImageInfo.Images.Image value) {
        if (imagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureImagesIsMutable();
          images_.set(index, value);
          onChanged();
        } else {
          imagesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Images.Image images = 1;</code>
       */
      public Builder setImages(
          int index, ImageInfo.Images.Image.Builder builderForValue) {
        if (imagesBuilder_ == null) {
          ensureImagesIsMutable();
          images_.set(index, builderForValue.build());
          onChanged();
        } else {
          imagesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Images.Image images = 1;</code>
       */
      public Builder addImages(ImageInfo.Images.Image value) {
        if (imagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureImagesIsMutable();
          images_.add(value);
          onChanged();
        } else {
          imagesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Images.Image images = 1;</code>
       */
      public Builder addImages(
          int index, ImageInfo.Images.Image value) {
        if (imagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureImagesIsMutable();
          images_.add(index, value);
          onChanged();
        } else {
          imagesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Images.Image images = 1;</code>
       */
      public Builder addImages(
          ImageInfo.Images.Image.Builder builderForValue) {
        if (imagesBuilder_ == null) {
          ensureImagesIsMutable();
          images_.add(builderForValue.build());
          onChanged();
        } else {
          imagesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Images.Image images = 1;</code>
       */
      public Builder addImages(
          int index, ImageInfo.Images.Image.Builder builderForValue) {
        if (imagesBuilder_ == null) {
          ensureImagesIsMutable();
          images_.add(index, builderForValue.build());
          onChanged();
        } else {
          imagesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Images.Image images = 1;</code>
       */
      public Builder addAllImages(
          java.lang.Iterable<? extends ImageInfo.Images.Image> values) {
        if (imagesBuilder_ == null) {
          ensureImagesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, images_);
          onChanged();
        } else {
          imagesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Images.Image images = 1;</code>
       */
      public Builder clearImages() {
        if (imagesBuilder_ == null) {
          images_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          imagesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Images.Image images = 1;</code>
       */
      public Builder removeImages(int index) {
        if (imagesBuilder_ == null) {
          ensureImagesIsMutable();
          images_.remove(index);
          onChanged();
        } else {
          imagesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Images.Image images = 1;</code>
       */
      public ImageInfo.Images.Image.Builder getImagesBuilder(
          int index) {
        return getImagesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Images.Image images = 1;</code>
       */
      public ImageInfo.Images.ImageOrBuilder getImagesOrBuilder(
          int index) {
        if (imagesBuilder_ == null) {
          return images_.get(index);  } else {
          return imagesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Images.Image images = 1;</code>
       */
      public java.util.List<? extends ImageInfo.Images.ImageOrBuilder> 
           getImagesOrBuilderList() {
        if (imagesBuilder_ != null) {
          return imagesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(images_);
        }
      }
      /**
       * <code>repeated .Images.Image images = 1;</code>
       */
      public ImageInfo.Images.Image.Builder addImagesBuilder() {
        return getImagesFieldBuilder().addBuilder(
            ImageInfo.Images.Image.getDefaultInstance());
      }
      /**
       * <code>repeated .Images.Image images = 1;</code>
       */
      public ImageInfo.Images.Image.Builder addImagesBuilder(
          int index) {
        return getImagesFieldBuilder().addBuilder(
            index, ImageInfo.Images.Image.getDefaultInstance());
      }
      /**
       * <code>repeated .Images.Image images = 1;</code>
       */
      public java.util.List<ImageInfo.Images.Image.Builder> 
           getImagesBuilderList() {
        return getImagesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ImageInfo.Images.Image, ImageInfo.Images.Image.Builder, ImageInfo.Images.ImageOrBuilder> 
          getImagesFieldBuilder() {
        if (imagesBuilder_ == null) {
          imagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ImageInfo.Images.Image, ImageInfo.Images.Image.Builder, ImageInfo.Images.ImageOrBuilder>(
                  images_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          images_ = null;
        }
        return imagesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Images)
    }

    // @@protoc_insertion_point(class_scope:Images)
    private static final ImageInfo.Images DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ImageInfo.Images();
    }

    public static ImageInfo.Images getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Images>
        PARSER = new com.google.protobuf.AbstractParser<Images>() {
      @java.lang.Override
      public Images parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Images(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Images> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Images> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ImageInfo.Images getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Images_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Images_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Images_Image_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Images_Image_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036src/main/java/image_info.proto\"{\n\006Imag" +
      "es\022\035\n\006images\030\001 \003(\0132\r.Images.Image\032R\n\005Ima" +
      "ge\022\020\n\010filename\030\001 \001(\t\022\014\n\004size\030\002 \001(\003\022\023\n\013cr" +
      "eatedTime\030\003 \001(\003\022\024\n\014modifiedTime\030\004 \001(\003"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Images_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Images_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Images_descriptor,
        new java.lang.String[] { "Images", });
    internal_static_Images_Image_descriptor =
      internal_static_Images_descriptor.getNestedTypes().get(0);
    internal_static_Images_Image_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Images_Image_descriptor,
        new java.lang.String[] { "Filename", "Size", "CreatedTime", "ModifiedTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
